# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170908_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='org',
            field=models.ManyToManyField(to='project.Organization'),
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='position',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='position',
            field=models.ManyToManyField(to='project.Position'),
        ),
    ]
