# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='type',
            new_name='content',
        ),
    ]
