# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifica', '0002_auto_20170908_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='permission',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='position',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='notifica.Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notify',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
