# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifica', '0002_auto_20170711_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
